### ISSUE TITLE
Short Cherry stabilizer doesn't follow the Cherry Spec

### ISSUE THREAD

**Issue by ifohancroft** [swill/kad#14]
I don't know about the long stabilizer but the short stabilizer that gets generated when you choose Cherry Stabs Only doesn't follow/differs from Cherry's specification.

P.S. I am falling to understand the numbers of the Cherry Stabilizer draw function well, but if you wouldn't mind explaining them, I can clone the repo, fix the issue and create a pull request or I can send you all the dimensions in millimeters of a stabilizer matching perfectly the spec, so you won't have to decipher it (although, maybe it's just me finding it tedious to decipher their size specs)

**Comment by swill** [comment]
It is actually intentional that it is not to spec.  I originally made it to spec, but there are situations where it is not ideal, so I adapted the cutout to perform better in real life.  One example is with plate mounted switches.  The official 2u cherry cutout is very sloppy compared to what we have, specifically for hand wired keyboards where you are not soldering into a PCB.

So in general, yes, it is not exactly to spec and that is intentional.  The cutout that I use is a real world improvement to the spec which is compatible with more types of switch/plate configurations.

Let me know if you are having issues of any kind and I will help you resolve.

Thanks for taking an interest and reporting this.  It is great to get feedback and engagement.

**Comment by ifohancroft** [comment]
Most welcome! Would you mind giving me examples of how the official 2u Cherry cutout is sloppy? I am planning on a build and was going to use it. I am especially interested when it comes to plate mounted builds with pcb and genuine stabilizers.

**Comment by swill** [comment]
If you are using a PCB, then it doesn't matter because your switch is soldered to the PCB.  If you are hand wiring, then the switch is clipped into the plate and that is the only thing holding the switch in place.  

The official 2u Cherry MX cutout has very limited surface area holding the switch in place when you are not using a PCB.  With hand wired keyboards, there have been reports of the switch feeling sloppy and having too much movement in the plate when not soldered to a PCB.
![image](https://user-images.githubusercontent.com/13644/66226900-eb1e3e00-e6a9-11e9-80fa-fce8996ba06b.png)

Using my builder, you have more material on the sides of the switch which help hold the switch in place better and reduces the movement of the switch in hand wired scenarios.
![image](https://user-images.githubusercontent.com/13644/66226428-c9708700-e6a8-11e9-87df-f8763a3155f1.png)

I hope this helps clear things up.  In your case, either will be fine because you are using a PCB.

**Comment by ifohancroft** [comment]
This definitely clears things up! Thank you very much! I will be using your cutout with PCB builds as well. Extra clipping space is always nice!
Btw can you confirm the sizes on this picture:
![tmp](https://user-images.githubusercontent.com/3461282/66229026-97cbe000-e6e9-11e9-8b8d-d49386f9dcd1.png)

I have measured from a generated SVG using InkScape and because of snapping and stuff it's not always the most correct.

**Comment by swill** [comment]
That looks right, but I have not gone through all of the measurements.

**Comment by ifohancroft** [comment]
Thank you!

**Comment by TweetyDaBird** [comment]
I'm trying to use these dimensions to make footprints usable for a FR-4 plate in KiCad, and getting a bit confused unfortunately.

Question one, what orientation are these intended for? It seems to me they are made with north-facing switches in mind, but as I said, I'm not sure.

Question two, what does this mean for the orientation of the PCB mount holes? As far as I know, the larger hole goes on the same end as the wire, with follows the LED? Is that correct?

**Comment by szafranski** [comment]
Looks like the pic is rotated 180 degree indeed
